# Generated by Django 2.2.8 on 2020-05-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200521_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Report Answer', 'verbose_name_plural': 'Report Answers'},
        ),
    ]
