# Generated by Django 2.2.8 on 2020-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200521_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='published',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_report_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
